### ISSUE TITLE
handleOpenURL method is not called on a cold boot when serving app locally

### ISSUE THREAD

**Issue by tavosansal** [isleofcode/corber#339]
I am using the custom url scheme plugin for cordova and I was not able to trigger the `handleOpenURL` method on a cold boot for the life of me. 

I created a blank ember app, installed ember-cordova as the single addon and nothing. So this ruled out plugin conflicts.

 Then I created a blank cordova app and sure enough it works. So now I have discovered that when the app is being served locally (`ember cdv:serve`) the event will never trigger on a cold boot (it does trigger on a warm boot). But if you build the app with (`ember cdv:build`) and then run it, the event does trigger on both cold and warm boot. So I am not entirely sure what the difference is or why this works.

Some links:

https://github.com/apache/cordova-ios/blob/master/guides/Cordova%20Custom%20URL%20Scheme%20Handling.md

https://github.com/EddyVerbruggen/Custom-URL-scheme#3-usage

**Comment by ahmacleod** [comment]
Using the `serve` or `start` commands, a "cold" boot through a custom url scheme first hits the livereload shell; at this point, your web app and its global `handleOpenURL` function are not yet loaded, so it's not possible to trigger the handler. Once the shell has redirected to your web app, loading through a custom url scheme works fine (i.e. a "warm" boot).

As you mentioned, this is not an issue with `build`, because the native app boots directly into your web app, and the handler is called as expected. We recommend you use this method for testing the cold boot scenario.
