### ISSUE TITLE
WKWebView forced by `corber prepare` when another webview has been specified

### ISSUE THREAD

**Issue by jeanduplessis** [isleofcode/corber#414]
We use `cordova-plugin-ionic-webview` however when running `corber prepare` it always forces `<plugin name="cordova-plugin-wkwebview-engine" />` to be added to config.xml and installed.

**Comment by alexblom** [comment]
Is the cordova-plugin-wkwebview-engine present in your plugins.json, package.json or config.xml?

When adding a platform, we default to WKWebView. When initting you would need to otherwise run `corber platform add ios --uiwebview`.

On a clean project I have added the platform this way, added ionic webview and run prepare without WK showing up.

**Comment by jeanduplessis** [comment]
@alexblom I must have had a rogue entry left in package.json for cordova-plugin-wkwebview-engine as I can't replicate this issue anymore. Sorry for that.

I can confirm using `corber platform add ios --uiwebview` meets our need since it doesn't add WKWebView. 

I think the --uiwebview flag in this case is a bit misleading as it doesn't actually add anything. May be worth considering renaming it in a future release.

Closing this issue now.

**Comment by alexblom** [comment]
Thanks. We should perhaps change that flag to --default-webview, or something along those lines.

**Comment by jeanduplessis** [comment]
Yeah --default-webview makes much more sense
