### ISSUE TITLE
If the application use ember-engines, after corber build, the .apk and .ipa will not working. 

### ISSUE THREAD

**Issue by LiShuxue** [isleofcode/corber#420]
Hi All,
1. I have a demo ember application: https://github.com/LiShuxue/ember-app.git
2. This application load an engine. https://github.com/LiShuxue/ember-app-adn-login.git
3. I use "corber build --platform=android --environment=development" to generate the android-debug.apk, but when i open the apk file, it show white screen.
4. I debug the apk , show me below error
GET file:///engines-dist/ember-app-adn-login/assets/engine-vendor.js net::ERR_FILE_NOT_FOUND
GET file:///engines-dist/ember-app-adn-login/assets/engine.js net::ERR_FILE_NOT_FOUND

Any one have any idea about that ? thanks

**Comment by alexblom** [comment]
I'll take a look at the sample app, but my first guess is we are mounting something with a `/` - perhaps an asset path?

**Comment by LiShuxue** [comment]
Hi @alexblom ,
Thanks for your reply.
Before i mount the engine like :  " `this.mount('ember-app-adn-login', {path: '/adn-login'}) ` ", it have issue.
I try to remove the "` /` " follow your suggest, use like this : " ` this.mount('ember-app-adn-login', {path: 'adn-login'})`  ", but it still have same error.

**Comment by alexblom** [comment]
Thanks. I'll take a look at the sample over the weekend.

**Comment by LiShuxue** [comment]
Hi.
Have you found anything ?

**Comment by alexblom** [comment]
I'll have to look into engines config more. 

If it helps in the interim I ran the repro project (thanks for including! -  your problem is the engine is adding tags like so:
`<script src="/engines-dist/ember-app-adn-login/assets/engine.js"></script>`

you want it to be:
`<script src="engines-dist/ember-app-adn-login/assets/engine.js"></script>`

**Comment by LiShuxue** [comment]
Hi @alexblom ,
Sorry for reply you so late...I have too many project need to release in my company.. too busy...
Anyway, continue our discussion.

yeah, like you said, maybe it will work like this `<script src="engines-dist/ember-app-adn-login/assets/engine.js"></script>`
but actually, the index.html will not load the script like that, it like this `<meta name="ember-app/config/asset-manifest" content="%7B%22bundles%22%3A%7B%22ember-app-adn-login%22%3A%7B%22assets%22%3A%5B%7B%22uri%22%3A%22/engines-dist/ember-app-adn-login/assets/engine-vendor.js%22%2C%22type%22%3A%22js%22%7D%2C%7B%22uri%22%3A%22/engines-dist/ember-app-adn-login/assets/engine.js%22%2C%22type%22%3A%22js%22%7D%5D%7D%7D%7D">`
and the asset-manifest.json will load the script like `"uri": "/engines-dist/ember-app-adn-login/assets/engine.js"`.
But i don't know how to change it in the asset-manifest.json file , is there any config file to change it automatically ?

**Comment by LiShuxue** [comment]
I changed the asset-manifest.json manully, like this`"uri": "engines-dist/ember-app-adn-login/assets/engine.js"`, but it still not working ..

![image](https://user-images.githubusercontent.com/20234214/33426097-517f9946-d586-11e7-8485-bc5eabe3b706.png)

![image](https://user-images.githubusercontent.com/20234214/33426149-77e921e2-d586-11e7-99ca-50897cc02082.png)

**Comment by LiShuxue** [comment]
Hi @alexblom ,
Do you have any suggestion ? I really don't know how to fix this issue.

**Comment by alexblom** [comment]
I'll be able to look again early next week for you.

**Comment by LiShuxue** [comment]
thanks

**Comment by LiShuxue** [comment]
Hi @alexblom , may i know how about this ?

**Comment by alexblom** [comment]
I was able to get your engine example running. The issue is that engines-dist has a leading slash as we figured above.

I don't know enough about engines to see how this is configurable, so I simply modified the meta tag to this (manually removing the leading slash from /engines-dist in both instances): `   <meta name="ember-app/config/asset-manifest" content="%7B%22bundles%22%3A%7B%22ember-app-adn-login%22%3A%7B%22assets%22%3A%5B%7B%22uri%22%3A%22engines-dist/ember-app-adn-login/assets/engine.js%22%2C%22type%22%3A%22js%22%7D%5D%7D%2C%22ember-app-adn-loginassets%22%3A%7B%22assets%22%3A%5B%7B%22uri%22%3A%22engines-dist/ember-app-adn-loginassets/engine-vendor.js%22%2C%22type%22%3A%22js%22%7D%5D%7D%7D%7D">`

Unfortunately I cannot tell you how to configure an engine to not default mount as `/`, but that seems like a reasonable question to ask them.

<img width="598" alt="screen shot 2017-12-15 at 11 26 49 am" src="https://user-images.githubusercontent.com/246898/34051077-38427afa-e18b-11e7-986d-113bb12a4ce8.png">

**Comment by LiShuxue** [comment]
yeah, it is working now, thanks !
