### ISSUE TITLE
Unable to "corber serve" and to debug Android native code at the same time

### ISSUE THREAD

**Issue by lone-cloud** [isleofcode/corber#462]
There is currently a major inconvenience with corber that prevents the dev from running "corber serve --platform=android" and debugging the native Java code via Android studio at the same time. Running "corber serve" seems to lock down the Android build files, which causes the Android studio assembleDebug gradle job to fail. It would ease development if these two can be run at the same time.

**Comment by alexblom** [comment]
Thanks for the report. I'm going to need to build a replication case, but it may be due to us watching/injecting the plugins directory e.g. https://github.com/isleofcode/corber/blob/master/lib/frameworks/ember/tasks/serve.js#L46-L53

So I can hit the same setup, are you using Ember/Vue/Angular/React?

**Comment by hoboman313** [comment]
I'm using ember.

**Comment by alexblom** [comment]
Thanks
