### ISSUE TITLE
Make default platform android on non-mac platforms for start command

### ISSUE THREAD

**Issue by DuBistKomisch** [isleofcode/corber#600]
Directly following on from https://github.com/isleofcode/corber/issues/581 which did so for the build command.

**Comment by alexblom** [comment]
I think in this case the issue was with `serve` vs `start`?

Start is generally smart enough to look at all of your platforms and list, whereas we had missed updating serve.

I'm just merging a PR that resolves this issue for serve - please let me know if I missed something obvious. And thanks for opening the separate issues!

**Comment by DuBistKomisch** [comment]
Apparently not, this is what I get:

```
 $ npx corber start
Corber Starting
spawn /usr/bin/instruments ENOENT
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: spawn /usr/bin/xcrun ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:362:16)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickCallback (internal/process/next_tick.js:181:9)
```

Or perhaps this is it "checking" what to do?
